
package ar.com.educacionit.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ar.com.educacionit.ws.CreateProductoDTO;
import ar.com.educacionit.ws.ObjectFactory;
import ar.com.educacionit.ws.Producto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductoWSService", targetNamespace = "http://ws.educacionit.com.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductoWSService {


    /**
     * 
     * @param arg0
     * @return
     *     returns ar.com.educacionit.ws.Producto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducto", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.GetProducto")
    @ResponseWrapper(localName = "getProductoResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.GetProductoResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/getProductoRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/getProductoResponse")
    public Producto getProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ar.com.educacionit.ws.Producto>
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findProductos", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.FindProductos")
    @ResponseWrapper(localName = "findProductosResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.FindProductosResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/findProductosRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/findProductosResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://ws.educacionit.com.ar/ProductoWSService/findProductos/Fault/InternalServerError")
    })
    public List<Producto> findProductos()
        throws InternalServerError
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns ar.com.educacionit.ws.Producto
     * @throws InternalServerError
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProducto", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.CreateProducto")
    @ResponseWrapper(localName = "createProductoResponse", targetNamespace = "http://ws.educacionit.com.ar/", className = "ar.com.educacionit.ws.CreateProductoResponse")
    @Action(input = "http://ws.educacionit.com.ar/ProductoWSService/createProductoRequest", output = "http://ws.educacionit.com.ar/ProductoWSService/createProductoResponse", fault = {
        @FaultAction(className = InternalServerError.class, value = "http://ws.educacionit.com.ar/ProductoWSService/createProducto/Fault/InternalServerError")
    })
    public Producto createProducto(
        @WebParam(name = "arg0", targetNamespace = "")
        CreateProductoDTO arg0)
        throws InternalServerError
    ;

}
